// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $character_id_ from "./routes/character/[id].tsx";
import * as $favoritos from "./routes/favoritos.tsx";
import * as $index from "./routes/index.tsx";
import * as $VisorChar from "./islands/VisorChar.tsx";
import * as $VisorChars from "./islands/VisorChars.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/character/[id].tsx": $character_id_,
    "./routes/favoritos.tsx": $favoritos,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/VisorChar.tsx": $VisorChar,
    "./islands/VisorChars.tsx": $VisorChars,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
